networks:
  proxy:
    driver: bridge
  metrics:
    driver: bridge

secrets:
  gf_admin_password:
    file: ./secrets/gf_admin_password.txt

services:
  # Reverse Proxy
  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - proxy
      - metrics

  # Homelab Dashboard
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./filesystem/config/heimdall:/config
    restart: unless-stopped
    networks:
      - proxy

  # Services
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - JELLYFIN_PublishedServerUrl=192.168.0.5 #optional
    volumes:
      - ./filesystem/config/jellyfin:/config
      - ./filesystem/media:/media
    ports:
      - 7359:7359/udp #optional - local network discovery
      - 1900:1900/udp #optional - DLNA
    restart: unless-stopped
    networks:
      - proxy

  # Home Automation
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: homeassistant
    environment:
      - TZ=Etc/UTC
    volumes:
      - ./filesystem/config/homeassistant:/config
      - /run/dbus:/run/dbus:ro
    network_mode: host
    restart: unless-stopped
    privileged: true

  avahi:
    build: ./avahi
    container_name: avahi
    network_mode: host
    restart: unless-stopped
    volumes:
      - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket

  # Metrics
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    networks:
      - metrics

  grafana:
    image: grafana/grafana
    container_name: grafana
    hostname: grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD__FILE=/run/secrets/gf_admin_password
    restart: unless-stopped
    networks:
      - metrics
    secrets:
      - gf_admin_password

volumes:
  caddy_data:
  caddy_config:
