networks:
  metrics:
    driver: bridge

secrets:
   gf_admin_password:
     file:./secrets/gf_admin_password.txt

services:
  # Homelab Dashboard
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /path/to/appdata/config:/config
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped

  # Services
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - JELLYFIN_PublishedServerUrl=192.168.0.5 #optional
    volumes:
      - ./filesystem/config/jellyfin:/config
      - ./filesystem/media:/media
    ports:
      - 8000:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    restart: unless-stopped

  filebrowser:
    image: filebrowser/filebrowser:s6
    container_name: filebrowser
    volumes:
      - ./filesystem/config/filebrowser:/config
      - ./filesystem/media:/srv
    ports:
      - 8001:80
    restart: always

  # Metrics
  prometheus:
    image: prom/prometheus
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
    ports:
      - 9090:9090
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - metrics

  grafana:
    image: grafana/grafana
    container_name: grafana
    hostname: grafana
    environment:
      -  GF_SECURITY_ADMIN_PASSWORD: /run/secrets/gf_admin_password
    restart: unless-stopped
    ports:
      - 3000:3000
    networks:
      - metrics
    secrets:
      - gf_admin_password
