global:
  scrape_interval: 1s
  evaluation_interval: 2s
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['host.docker.internal:9090']
  - job_name: 'docker'
    static_configs:
      - targets: ['host.docker.internal:9323']
